### ISSUE TITLE
Slow performance when running `oscap oval validate --schematron`

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1260]
#### Description of Problem:
When running `oscap oval validate --schematron ssg-oval.xml`, the performance is terrible. It can take 2-5 minutes to complete and takes a ton of system resources whereas XCCDF and DS validation can take less than 7 seconds.

#### OpenSCAP Version:
Current

#### Operating System & Version:
Fedora, RHEL

#### Steps to Reproduce:

1. Run oscap oval validate --schematron ssg-rhel7-oval.xml or check out Jenkins output.
2. 
3. 

#### Actual Results:
```174/221 Test #153: validate-ssg-rhel7-oval.xml ..............................................   Passed  284.71 sec```

#### Expected Results:
At least 10 secs or under would be nice.

**Comment by jan-cerny** [comment]
I have profiled the command and I have found that most of the time it spends inside functions from `libxslt`. We cannot change the XSLT file, because then we will validate against a different baseline, which could possibly get different results than with the original file. Therefore to fix it we need to use a different (faster) XSLT library to process the XSLT.

**Comment by redhatrises** [comment]
@jan-cerny I don't suppose that we can figure out how to speed up the functions and submit upstream?
