### ISSUE TITLE
Typo in auditd kernel module (un)loading remediation script

### ISSUE THREAD

**Issue by jmnielsen7** [OpenSCAP/openscap#1305]
#### Description of problem:

Running the following remediation command results in a error that traces to an apparent typo in the SSG remediation script for RHEL 6 that addresses auditd hardening.

Command:
`sudo oscap xccdf eval --remediate --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig-rhel6-disa --results ~/results.xml ./ssg-rhel6-ds.xml`

The human readable output in the SSG HTML format report for non-compliance under the **_Evaluation Messages_** section: 

> Fix execution completed and returned: 0
> 
> `sed: -e expression #3, char 13: unknown command: `F'`
>
> `sed: -e expression #3, char 13: unknown command: `F'`
> 
> Failed to verify applied fix: Checking engine returns: fail

I traced it to this code block where there is a trailing capital 'F' after a semicolon in a sed command:

> 	\# Check if particular audit rule is already defined
> 	IFS=$'\n'
> 	matches=($(sed -s -n -e "\;${pattern};!d" -e "/${arch}/!d" -e "/${group}/!d;F" /etc/audit/rules.d

#### SCAP Security Guide Version:

0.1.43

#### Operating System Version:

RHEL 6.10

#### Workarounds:

Are there any temporary workarounds? I see the code as reported in the HTML but am not sure where it actually comes from in the SSG unzipped content. In the ssg-rhel6-ds.xml file itself? A quick removal of the errant 'F' should do the trick if I can locate the right file to edit.

**Comment by shawndwells** [comment]
Hey @jmnielsen7 , thanks for reporting this! This issue is about content versus the OpenSCAP scanner itself. Since it appears you're using RHEL, a few options:

- The SCAP Security Guide (SSG) content shipping in RHEL is supported by Red Hat. Means you can utilize your Red Hat support subscription and open a case direct with Red Hat. They'll fix it and ship an errata. Cases with Red Hat carry support SLAs whereas upstream/github is a community effort;

- If you'd like to engage with the community through GitHub, we'll wan to move the case over to https://github.com/ComplianceAsCode/content. We can't administratively do this -- you'll need to copy/paste your case there.

- If you're interested to submit a PR to fix this, it appears the offending line is in the bash remediations (https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh#L88). We'd be happy to help you through the PR process if you're new to GitHub workflow!

**Comment by jmnielsen7** [comment]
@shawndwells  Okay. Seems like the name of that issue board changed. I don't recall it being ComplianceAsCode a year ago and I couldn't find an SSG tag while I saw lots of other ones, so I got confused and posted here for lack of a clearer place to report it. I'll paste this over there though. Thanks!

**Comment by shawndwells** [comment]
@jmnielsen7 no worries. Project name did change from github/openscap/scap-security-guide to github/complianceascode maybe a year ago. Intent was to show how the content is separate from the OpenSCAP scanner, and how the content project now does more than SCAP (e.g. Ansible, opencontrol, etc).

Closing this ticket because https://github.com/ComplianceAsCode/content/issues/3833 is now open.
