### ISSUE TITLE
Ansible playbook output has incorrect permissions

### ISSUE THREAD

**Issue by ghost** [OpenSCAP/openscap#1380]
#### Description of Problem:

Ansible playbooks have the execute bit set on them after creation which is not needed.

#### OpenSCAP Version:

1.2.17 and 1.3.1

#### Operating System & Version:

CentOS 7.6

#### Steps to Reproduce:

1. yum install openscap-scanner
2. oscap xccdf generate fix --fix-type=ansible --output=myplaybook.yml ...
3. ls -l myplaybook.yml

#### Actual Results:

Playbook permissions are 0700 (rwx------)

#### Expected Results:

Execute bit should not be set on output playbooks as they are not executable like the shell scripts.

#### Additional Information / Debugging Steps:

I also manually built and ran the latest version from GitHub on a test system and ended up with the same result. I left out the profile and data source information from the steps because it doesn't matter which are used as the important bit are the fix type.

**Comment by evitalis** [comment]
I was going to try and do a PR for this but was not able to find where this file is written. Can I please get pointed in the right direction or has this already been resolved?

**Comment by jan-cerny** [comment]
Hi, thank you very much for reporting this issue.

As a workaround, you can use stdout redirection instead of `--output`, for example:

```
oscap xccdf generate fix --fix-type ansible --profile ospp \
/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml > playbook.yml
```

> I was going to try and do a PR for this but was not able to find where this file is written. Can I please get pointed in the right direction or has this already been resolved?

That's great! It hasn't been resolved yet.

I think this part of code writes the output file:

https://github.com/OpenSCAP/openscap/blob/2c04d939b93b7394f76adb86bf0b24ff0d76d963/utils/oscap-xccdf.c#L922-L925

However, the code is common for both Ansible and Bash remediations. I think the Bash scripts should be written with the executable bit set, so you will need to have a condition that sets different permissions based on values of `--fix-type` and `--template` arguments.
