### ISSUE TITLE
Some STIG rules are not behave as expected 

### ISSUE THREAD

**Issue by vivekhegde7** [OpenSCAP/openscap#1484]
#### Steps to Reproduce: 

Windows   Server 2019 Create symbolic links user right must only be assigned to the   Administrators group.
--

1.  Check Content
Verify the effective setting in Local Group Policy Editor.

Run "gpedit.msc".

Navigate to Local Computer Policy >> Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment.

If any accounts or groups other than the following are granted the "Create symbolic links" user right, this is a finding:

- Administrators

2. Fix Text
Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> "Create symbolic links" to include only the following accounts or groups:

- Administrators

3. 

#### Additional Information / Debugging Steps: If the value is changed as mentioned in Fix, even also Rule is Failing.

Is this Probe issue Or any other issue.?

**Comment by redhatrises** [comment]
@vivekhegde7 what STIG content are you using and can you provide the STIG datastream?

**Comment by me-shubh** [comment]
@redhatrises 

> @vivekhegde7 what STIG content are you using and can you provide the STIG datastream?

@redhatrises So what is it? The probe issue or any other?

**Comment by evgenyz** [comment]
It is still unclear, because reporter did not provide neither any means of identification of the content in use, nor the logs of the scan run.

Also, this bug is most likely related to the content itself, but without aforementioned information it is hard to imagine that anyone would be able to triage this issue.

I propose marking such issues as `unclear` (or any other suitable tag), and close them after, say, a month of inactivity.

**Comment by evgenyz** [comment]
Closing as unclear and inactive.
