### ISSUE TITLE
SCE is disabled for Windows

### ISSUE THREAD

**Issue by ArtsiomMusin** [OpenSCAP/openscap#1486]
This is a follow up on this question https://serverfault.com/questions/1003058/how-to-run-openscap-with-my-own-powershell-script

As far as I can see SCE was disabled during the build as the build didn't pass here: https://ci.appveyor.com/project/OpenSCAP/openscap/build/master-456
Do you have any plans to fix it and enable SCE for windows?

This is a nice feature we use for some customs script on linux but also wanted to try it on windows.

**Comment by ArtsiomMusin** [comment]
we tried openscap 1.2.17 with custom scripts on windows and it worked well. It seems after removing cygwin something is broken in SCE...

**Comment by ggbecker** [comment]
OpenSCAP 1.3.X for Windows does not use cygwin anymore and the SCE plugin was not properly ported to be build using appveyor+visual studio. The SCE plugin implementation is based on forks, pipe, etc... things that are not natively supported by Windows but cygwin was able to provide enough emulation to make it work for OpenSCAP 1.2.X.

It requires quite some effort to port it since you need to rewrite core functionalities of SCE.
In the process of discovering this I started changing the SCE code to compile on Windows. If you would like to have a starting point and to contribute, here is the branch: https://github.com/ggbecker/openscap/tree/enable-sce-2

And here it is the build output on appveyor from the latest commit: https://ci.appveyor.com/project/GabrielBecker/openscap/builds/31550328

Also, one valid attempt would be compiling OpenSCAP 1.3.X using cygwin, but the instructions from OpenSCAP 1.2.X are not valid to OpenSCAP 1.3.X anymore since it uses now CMake instead of autoconf.

Maybe @jan-cerny has something to add here.

**Comment by jan-cerny** [comment]
@jan-cerny Yes, @ggbecker is correct. I will only add that we removed Cygwin and enabled Visual Studio instead to make it easier for Windows developers to contribute patches.

**Comment by ArtsiomMusin** [comment]
thanks @ggbecker Maybe we will have some free time next months and will try to contribute... unless you fix it before us :slightly_smiling_face:
