### ISSUE TITLE
OVAL object 'file_object' is not supported on OpenScap for Windows

### ISSUE THREAD

**Issue by kemanik** [OpenSCAP/openscap#1518]
#### Description of Problem:
I tried to scan windows content on Windows 7 through oscap ( oscap oval eval). I have result="unknown" because of "OVAL object 'file_object' is not supported". When are you going to support file prober on OpenScap for Windows?

#### OpenSCAP Version:
OpenSCAP-1.3.2-win32

#### Operating System & Version:
Windows 7

#### Steps to Reproduce:

oscap oval eval --results res2.xml oval_org.cisecurity_def_2.xml 
[oval_org.cisecurity_def_2.xml.zip](https://github.com/OpenSCAP/openscap/files/4516195/oval_org.cisecurity_def_2.xml.zip)
#### Actual Results:
<object id="oval:org.cisecurity:obj:1" version="61" flag="not collected">
            <message level="warning">OVAL object 'file_object' is not supported.</message>
          </object>

[res2.zip](https://github.com/OpenSCAP/openscap/files/4516201/res2.zip)

#### Expected Results:
Collected items

**Comment by evgenyz** [comment]
Hey, @kemanik! Short answer – whenever somebody will submit a PR with Windows™ support for `file_probe`.

Currently we don't have a dedicated member in our community for this platform, and, while we are glad to review and accept any contributions related to it, there is not much of a roadmap. Sorry.

As a side note. Implementation might be a bit harder than usual, because there are actually two `file_object`s: in UNIX and Windows definitions (with different `file_state`s).
