### ISSUE TITLE
Tailoring file does not seem to be picked up

### ISSUE THREAD

**Issue by nielsvbrecht** [OpenSCAP/openscap#1542]
#### Description of Problem:
I have created a customization file with SCAP workbench for the RHEL7 CIS benchmark. I have unchecked the Level 2 controls and some others. Which results in around 203 controls being applicable.

I run a compliance scan with oscap within my CI/CD pipeline with the following command:
"sudo /usr/bin/oscap xccdf eval --report /tmp/oscap-reports/results-{{user `builder_name`}}-{{user `build_id`}}.html --profile xccdf_org.ssgproject.content_profile_cis --tailoring-file /opt/scap-security-guide/tailoring-xccdf.xml /opt/scap-security-guide/scap-security-guide-0.1.50/ssg-rhel7-ds-1.2.xml",

During the Linux build (done with Packer and Ansible) I copy over the tailoring file from my repo to the target VM which completes succesfully. 
After running the Ansible provisioner I run the shell provisioner in Packer to run the openscap scan on the target VM with the command mentioned above.

The results file as html is published as an artifact in Azure DevOps and still shows all controls being checked.

#### OpenSCAP Version:
1.2.17 (rpm)
1.3.3 (built from source)

#### Operating System & Version:
Redhat Enterprise Linux 7.7 (on Azure)

#### Steps to Reproduce:

1. "sudo /usr/bin/oscap xccdf eval --report /tmp/oscap-reports/results-{{user `builder_name`}}-{{user `build_id`}}.html --profile xccdf_org.ssgproject.content_profile_cis --tailoring-file /opt/scap-security-guide/tailoring-xccdf.xml /opt/scap-security-guide/scap-security-guide-0.1.50/ssg-rhel7-ds-1.2.xml"

#### Actual Results:
+/-200 controls report as passed 69 as failed.

#### Expected Results:
+/-200 controls report as passed and 69 as not checked.

#### Additional Information / Debugging Steps:

Scap security guide 0.1.50

**Comment by jan-cerny** [comment]
Hi @nielsvbrecht,

Make sure that you use the right profile ID in `--profile` option. The ID of the customized profile needs to be used instead of the ID of the original profile. Open the tailoring file `tailoring-xccdf.xml`, find the `xccdf:Profile` element and check if the `id` attribute of this element. It needs to be the the same ID that you use as `--profile` option of `oscap` command. If the `id` attribute is different, change the command accordingly.

If this doesn't help, please attach the tailoring file to the bug report.

**Comment by nielsvbrecht** [comment]
Thanks Jan, I will try it out!

**Comment by nielsvbrecht** [comment]
Proposed solution worked indeed, thanks I will close the issue.
