### ISSUE TITLE
[SCAP.R.2850] system charecteristics have collected objects but don't have system data

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1640]
### Description of Problem:
When I evaluated  r2850-rhel-datastream.xml from [SCAP 1.3 validation test suite](https://csrc.nist.gov/CSRC/media/Projects/scap-validation-program/documents/SCAP1.3ValidationTestContent_1-3.0.0.0.zip) SCAPVAL told me that I have problem RES-181-1 in the ARF results.

According to the SCAPval HTML report, the problem with ARF results is: 

> Error if oval-res directives definitions have @content='full' or @content is not provided and oval-res:oval_system_characteristics does not have both oval-res:collected_objects and oval-res:system_data.

By looking to the ARF file, I can see that there is oval_system_characteristics element that contains collected_objects element but doesn't contain system_data element. It might be because all objects within the collected objects don't exist. 

#### OpenSCAP Version:
1.3.4 

#### Operating System & Version:
f32/el8

#### Steps to Reproduce:

This was reproduced before #1638 was fixed.

Probably won't be reproducible this way if #1638 is fixed but I think it might be reproducible some other ways after it. I think it could be reproduced by any OVAL file where all OVAL objects are evaluated as "does not exist" during the scan. But this hypothesis needs to be verified. I insist you create a more isolated reproducer that doesn't depend on other issue before you start fixing this issue.

1. oscap xccdf eval --results-arf results_arf.xml --profile xccdf_gov.nist.validation_profile_r2850-rhel r2850-rhel-datastream.xml
2. java -jar /opt/scapval/scapval-1.3.5.jar -valreportfile report.html -resultfile results_arf.xml -scapversion 1.3
3. firefox report.html

#### Actual Results:
RES-181-1 fails

#### Expected Results:
RES-181-1 passes

#### Additional Information / Debugging Steps:

I assume that adding an empty system_data will not solve it because system_data must have children items.

**Comment by vojtapolasek** [comment]
Hello, here are steps to reproduce.
1. make sure that there is no file /foo.txt on your system
2. 2. run oscap oval eval --results results.xml reproducer.xml
3. the check will fail.
4. Open the file and see that there is no element system_data
5. create the file /foo.txt and make sure that oscap can read it
6. run the test again
7. the check should pass and in the results the system_data element appears.

**Comment by vojtapolasek** [comment]
[reproducer.xml.zip](https://github.com/OpenSCAP/openscap/files/6022572/reproducer.xml.zip)

**Comment by vojtapolasek** [comment]
It seems that there is a discrepancy between OVAL specification and SCAP 1.3 specification.
We are considering the case when within the <directives> node, there are  definitions either with parameter content set to "full" or without the content parameter at all.
SCAP 1.3 mandates that in this case, both "collected_objetcs" and "system_data" exist within the "oval-system-characteristics". However, we are encountering a special case, when the object which is being checked does not exist. In this case, the object is placed within the "collected_objects", but it does not have any reference_item assigned. that is because no item has been found. And no item can be therefore put within the "system_data" element. OVAL language specification does not allow empty "system_data" element. This is a discrepancy between two standards.

**Comment by jan-cerny** [comment]
@vojtapolasek I concur.

I would add that it is also mentioned in the ContentEnumeration type definition in OVAL where the "full" value is explained that it means collected_objects and system_data properties of the system_characteristics should be included. So I would say that the discrepancy is also in the OVAL itself.

Just to clarify: this issue is a corner case when all evaluated objects are evaluated as "does not exist" which leads to empty "system_data" element.
