### ISSUE TITLE
Unable to run DISA Stig rules on Centos7

### ISSUE THREAD

**Issue by Siddhu1096** [OpenSCAP/openscap#1770]
Hi Team,

Since we don't have DISA stig rules particularly for CentOS7, I was trying to run rhel7's stig rules. But, when I try to run, all the rules are giving output as "Not Checked". Is there any way to scan my centos 7 machine with DISA Stig rules? 
Also, I have downloaded stig file from a third party website, but the end result was the same. Any help would be appreciated. 
This is the example outputs
When I try to run third-party stigs
![image](https://user-images.githubusercontent.com/22325249/123054142-34846300-d422-11eb-864e-7886d24fee1c.png)

When I try to run DISA Stig rules provided by OpenSCAP
![image](https://user-images.githubusercontent.com/22325249/123054493-8a590b00-d422-11eb-90a3-49406c95599d.png)

**Comment by jan-cerny** [comment]
Hi Siddhu,

Unfortunately, STIG for CentOS doesn't exist.

The file in your first example is a manual checklist, it contains only the metadata but it doesn't contain automated checks. You can see that from the word "Manual" in the file name. It's designed for other use cases than automated compliance checks.

The content in ssg-rhel7-ds.xml is dedicated to RHEL 7. The checks first check that the system is really a RHEL 7 system and if it isn't it returns notapplicable and doesn't perform the actual check.

As a hack, you can try to manually remove these elements from the ssg-rhel7-ds.xml:

```
      <xccdf-1.2:platform idref="cpe:/o:redhat:enterprise_linux:7"/>
      <xccdf-1.2:platform idref="cpe:/o:redhat:enterprise_linux:7::client"/>
      <xccdf-1.2:platform idref="cpe:/o:redhat:enterprise_linux:7::computenode"/>
      <xccdf-1.2:platform idref="cpe:/o:redhat:enterprise_linux:7::server"/>
      <xccdf-1.2:platform idref="cpe:/o:redhat:enterprise_linux:7::workstation"/>
```

By removing them you effectively remove the operating system checks. Then if you run the scan it will give you some results, but they might be false in some cases, simply because you are running it on a different system.

CentOS is not an exact copy of Red Hat Enterprise Linux. There may be configuration differences that produce false positives and/or false negatives. CentOS has its own build system, compiler options, patchsets, and is a community supported, non-commercial operating system. CentOS does not inherit certifications or evaluations from Red Hat Enterprise Linux. As such, some configuration rules (such as those requiring FIPS 140-2 encryption) will fail on CentOS.

**Comment by Siddhu1096** [comment]
Thank you so much for the detailed explanation
