### ISSUE TITLE
libopenscap.so.25: No such file or directory

### ISSUE THREAD

**Issue by jfrverdasca** [OpenSCAP/openscap#1774]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:
oscap: error while loading shared libraries: libopenscap.so.25: cannot open shared object file: No such file or directory

#### OpenSCAP Version:
latest

#### Operating System & Version:
ubuntu 20.04 with python 3.7

#### Steps to Reproduce:
Follow the instructions to build and install (with python3.7 bindings, NOT TESTED WITHOUT)

**Comment by jan-cerny** [comment]
@jfrverdasca  Can you paste the build output?

**Comment by jfrverdasca** [comment]
> @jfrverdasca Can you paste the build output?

Install ouput:
[oscap_install_logs.txt](https://github.com/OpenSCAP/openscap/files/6772379/oscap_install_logs.txt)

Install warnings:
[oscap_warnings.txt](https://github.com/OpenSCAP/openscap/files/6772384/oscap_warnings.txt)

I hope it was helpful.

**Comment by jan-cerny** [comment]
This is probably an unwanted side effect of https://github.com/OpenSCAP/openscap/pull/1765 where we stopped to set rpath on installed binaries. By default, the `make install` command installs it to `/usr/local/` but the `/usr/local/lib` isn't normally a path where the linker would look for dynamic libraries.

You can try to install the files to `/usr` instead of `/usr/local` by adding `-DCMAKE_INSTALL_PREFIX=/usr` to the `cmake` command. Another way is to add the path where `libopenscap.so` is located to your `LD_LIBRARY_PATH`, for example, you can run `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"`.

**Comment by jfrverdasca** [comment]
Thank you for your time and help!

When I ran into this issue, I used the 1.3.4 branch of git that doesn't have this issue. I don't know if the installation method has changed but in this version it is installed and works correctly
