### ISSUE TITLE
Stig Viewer error with oscap

### ISSUE THREAD

**Issue by Siddhu1096** [OpenSCAP/openscap#1797]
#### Description of Problem:
I am trying to generate report-stig.xml output from the command ``` oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa --stig-viewer results-stig.xml ssg-rhel7-ds.xml``` . Even though I am getting an output, When I try to import that in stig viewer, it is getting errored out.

#### OpenSCAP Version:
OopenSCAP version is 1.2.17

#### Operating System & Version:
RHEL 7.7

#### Steps to Reproduce:

1. Run ```oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa --stig-viewer results-stig.xml ssg-rhel7-ds.xml```
2 . Open stig viewer, open the stig profile (ssg-rhel7-ds.xml) 
3. Create checklist
4. Import result-stig.xml file
5. Getting an error after importing 
![image](https://user-images.githubusercontent.com/22325249/129726831-d675673c-8db7-4c52-ae3c-081c9e9e7f73.png)

#### Actual Results:

Reference ID's are not there in stigs

#### Expected Results:
Reference ID's should be matched, verified after hardening and should be able to view the status as reviewed or not

Any help would be appreciated

**Comment by ggbecker** [comment]
Depending on the version of DISA STIG benchmark you have in STIG viewer and the content (ssg-rhel7-ds.xml) used, there can be a misalignment since DISA has renegerated references in STIG RHEL7 V3.

RHEL 7.7 has probably a very older version of scap-security-guide that contains references to older STIG RHEL7, probably something around RHEL7 STIG V2.

You can either update to RHEL7.9 and get a fresh scap-security-guide package, or use the datastream built from the upstream that you can find in the releases page from ComplianceAsCode/content project: https://github.com/ComplianceAsCode/content/releases/download/v0.1.61/scap-security-guide-0.1.61.zip

**Comment by ggbecker** [comment]
I think this is not an OpenSCAP issue. Please reopen if the solution above doesn't work for you.
