### ISSUE TITLE
 OCIL: The Open Checklist Interactive Language

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#193]
Rationale: OCIL is a standard from SCAP family. It allows for interaction with auditor by means of questionares. Currently OpenSCAP lacks implementation of this standard.

Deliverable: New OpenSCAP module. Integration with `oscap xccdf eval`. 

This is big idea.

**Comment by isimluk** [comment]
http://scap.nist.gov/specifications/ocil/#resource-2.0

**Comment by matusmarhefka** [comment]
This is still valid, we might work on it in the future.

**Comment by DimaZzZz101** [comment]
Good afternoon everyone! Well, you closed the issue, because “nobody cares,” although you drag around an entire component with thousands of lines in the generated documents, as well as a ton of references to OCIL in the Rules. How can this be useless if almost every standard has a conditional MANUAL requirement that OVAL will not physically check, but for example the reviewer will be able to mark the requirement as fulfilled/not fulfilled in the OCIL checklist.

А теперь воспользуйтесь переводчиком, господа. На кой черт все время фиксить правила под кучу систем, супер-мудренной сборочной системой, при том, что в доке нет нормальной инфы, а как же эти правила писать (например нет адекватного пояснения, почему обваливается сборка документа при линковке некоторых OVAL Definitions, я подозреваю, что это из-за привязки ОС к процессу сборки), если бы можно было допилить систему до полноценного использования NIST-схем (да они устаревшие, но они же есть). Сорри за негатив, просто мне откровенно не понятно, в честь чего было принято решение забить на OCIL.

**Comment by evgenyz** [comment]
I've closed the issue because those who are _actively working on the project_ do not care about this issue. The project welcomes third-party pull requests, though. But if it is a big feature I'd advice to write a proposal in form of a feature before actually implementing it.

Кнопка «Fork» находится на главной странице.
