### ISSUE TITLE
HASH

### ISSUE THREAD

**Issue by Raumin05** [OpenSCAP/openscap#1965]
Hello,

Excuse me, is possible to have the OpenSCAP workbench file hash ? 

If not, Why ? 

Thank you 

Have a good day

**Comment by Raumin05** [comment]
OK thank you. Where find it ? @evgenyz

**Comment by evgenyz** [comment]
Right next to the file.

**Comment by Raumin05** [comment]
Thanks

That's ? Can you give me the link ?

**Comment by Raumin05** [comment]
@evgenyz

**Comment by ggbecker** [comment]
For the benchmarks we provide the hash for the release artifact (zip file) here for example: https://github.com/ComplianceAsCode/content/releases/tag/v0.1.67

If this is not what you are looking for, you need to be more specific, because your request doesn't contain information enough for us to provide a clear answer.
