### ISSUE TITLE
PUADIManager:win32/sepdot virus found in Windows Installer 1.3.0

### ISSUE THREAD

**Issue by Zealot88** [OpenSCAP/openscap#2132]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:
Virus found in the [Base Windows 1.3.0 download ](https://github.com/OpenSCAP/openscap/releases/download/1.3.0/OpenSCAP-1.3.0-win32.msi)
![image](https://github.com/OpenSCAP/openscap/assets/142270303/4f6bce86-ef56-4c8c-b4c1-cfac411772d7)

#### OpenSCAP Version:
1.3.0

#### Operating System & Version:
Windows 10

#### Steps to Reproduce:

1. Download the installer from above link
2. Scan with Windows Defender; above virus is detected (PUADIManager:Win32/sepdot)
3. Delete file (unless you want to install a virus)

#### Actual Results:
Found a virus in installer

#### Expected Results:
No virus found

**Comment by Mab879** [comment]
I'm thinking this might be a false positive. I reran the [VirusTotal](https://www.virustotal.com/gui/file/adfb73086b191c607d1ded60d36d5eec50e044491501428a835c0eedcd117743) scan the installer file today at about 2024-07-01 12:15 UTC and there are no detections. Even the "Microsoft" scanner on VirusTotal gives the installer a clean bill of health. I will also note the it seems that it is calling the installer a PUA (potentially unwanted application), so technically not a virus. 

I also note as according to VirusTotal is the same file that has been around since mid-2022. So I think the scanner vendor needs to make some tweaks.
