### ISSUE TITLE
Evaluate SSG shorthand format

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#289]
I wonder whether it would be possible to process SCAP Security guide "shorthand" format in OpenSCAP directly, eg `oscap shothand eval file.xml`. The idea behind this is that a SSG content writer will be able to easily check his content during its development before he adds it to the build system.

**Comment by mpreisler** [comment]
I am against including this in OpenSCAP. shorthand is a SSG specific format and this workflow can be achieved with trivial scripting around tools already available in SSG.

**Comment by isimluk** [comment]
I think this is very good idea that would help content authors. Although, I echo what Martin said, the OpenSCAP Base is not right place to implement this.

The shorthand format evolves over time and whole implementation is in SSG. When we put another implementation of shorthand to OpenSCAP we would need to maintain them in sync, otherwise the usefulness deteriorates over time.

I propose to have this issue filed against SSG. In SSG, we can start creating/maintaining bash script, that builds a small datastream from single shorthand file. Then the evaluation is easy.
