### ISSUE TITLE
Provide --generate-remediations next to --remediate in `oscap` tool

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#338]
A lot of enterprise admins run huge deployments with configuration management systems. Executing the remediations makes no sense to them. Instead they want a script so they can alter their configuration system settings with it.

This would be a very handy shortcut, similar to `--remediate`.

**Comment by rsprudencio** [comment]
I think we can rename 'generate fix' to 'generate remediation and add this shortcut to eval so it can also generate the remediation instead of running it, so we can get some consistency in fix/remediation naming.

**Comment by evgenyz** [comment]
Will `oscap xccdf generate fix --fix-type=bash` (v1.3+) generate what is needed here?

**Comment by jan-cerny** [comment]
I don't exactly understand the proposal, but I assume that Martin asks to generate the remediation during the scan, in a single command. Since the remediation can be easily generated after scan, I think this is only a convenience short-cut or, let's say, UX improvement. I see inconsistency in the current implementation: you can generate the HTML report during the scan, but you can't generate remediation during the scan.
