### ISSUE TITLE
oscap generate fix shouldn't require result-id if there is just one TestResult element

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#340]
It should be obvious which TestResult I want if there is just one available.

I would even say that if there are more it should just choose the latest according to the timestamps.

**Comment by isimluk** [comment]
Agreed, that the ui should be improved here.

Just, things are more complex under the hood. Without ID, we are doing much more different things than with ID. https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/oscap-xccdf.c#L764

**Comment by mpreisler** [comment]
Maybe it makes more sense to provide this functionality elsewhere and keep this for backwards compat. We are limited here because the past implementation was strange.

`generate remediation` or something would work. with a deprecation warning in `generate fix`.

**Comment by rsprudencio** [comment]
This ticket doesn't make sense anymore because `oscap generate fix` changed the behavior in #597 

If there is no --result-id argument, it will fallback to the profile if provided, if profile is not provided as well, it will fallback to (default) profile. So if we remove the need for --result-id, it will not generate fixes based on results anymore and always fallback either to provided profile or to (default) profile.

**Comment by mpreisler** [comment]
I think we can close this then.
