### ISSUE TITLE
User manual - Building on Windows - obsoleted way

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#384]
https://github.com/OpenSCAP/openscap/blob/maint-1.0/docs/manual/manual.adoc#54-building-openscap-on-windows

1) we should not refer to `git://git.fedorahosted.org/git/openscap.git`, but rather to github
2) instead of `-b portable` should be probably `-b master`

We should ensure, that we can (still) can build it on Windows

**Comment by jan-cerny** [comment]
OK, however keep in mind that we have decided to have instructions for windows build updated only in master branch, because windows build can be make only in master branch, so the instructions are applicable only in master branch. For further details, please see discussion in https://github.com/OpenSCAP/openscap/pull/222

**Comment by matejak** [comment]
Closed by #1080
