### ISSUE TITLE
OVAL tests should be allowed to reference only objects of same type

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#401]
Tests referencing objects of different type should be rejected by OpenSCAP.
For example, textfilecontent54_object can be referenced only from textfilecontent54_test, but NOT from sysctl_test. Such referencing is wrong according to schematron validation.

In my opinion, OpenSCAP should check consistency of this during the evaluation.

Credits for discovering this issue goes to @praving5

For further information, please see mailing list thread:
https://www.redhat.com/archives/open-scap-list/2016-April/msg00052.html

**Comment by praving5** [comment]
Thanks @jan-cerny for posting it here.

**Comment by iankko** [comment]
@jan-cerny 
> Tests referencing objects of different type should be rejected by OpenSCAP.
For example, textfilecontent54_object can be referenced only from textfilecontent54_test, but NOT from sysctl_test. Such referencing is wrong according to schematron validation.

Hi Jan,
  thanks for looking further into this. Just to confirm this bug report is about referencing of different type of object than expected by the "declaration" of test, right? (e.g. ```sysctl_object``` from ```textfilecontent54_test``` as has been reported).

The fix for this issue won't affect the situation, when you create something like the following:
* create ```unix:file_object``` to get file paths,
* store the collected results into variable,
* use that variable subsequently in ```<textfilecontent54_test>``` to process the collected data further,
* now finally (via another local variable) the final test will be of ```<variable_test>``` type acting on content of local variables, previously collected from different objects?

To make the long story short, what I want to assure myself being that even after patch for this issue is applied, it will still be possible to pass one type of object to different type of object via declaring intermediary ```<local_variable>``` OVAL object?

Asking, because we use / rely on this functionality in SSG -- the implementation of ```audit_rules_privileged_commands``` OVAL check uses this logic:
* https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/input/oval/audit_rules_privileged_commands.xml

and should the fix for this issue break e.g. the above OVAL, we (in SSG) would like to know sooner (to have chance to reimplement it different way).

Or is the performing additional level of validation on such (currently existing) OVAL an answer to this (if it passes now, we don't need to worry about it)?

Thanks for your time in advance
Jan

**Comment by jan-cerny** [comment]
@iankko 

> Just to confirm this bug report is about referencing of different type of object than expected by the "declaration" of test, right?

Yes, that is exactly what I meant.

> To make the long story short, what I want to assure myself being that even after patch for this issue is applied, it will still be possible to pass one type of object to different type of object via declaring intermediary <local_variable> OVAL object?

It definitely must be possible. It is valid use-case in my opinion.

> Or is the performing additional level of validation on such (currently existing) OVAL an answer to this (if it passes now, we don't need to worry about it)?

I haven't  made the fix for this bug yet. I don't even know yet how the patch will be done. But I know that this issue is reported when you perform schematron validation (`oscap oval validate --schematron file.xml`). So I think that yes, performing an additional level of validation should be the answer to that.

But thank you very much for pointing this out.

**Comment by jan-cerny** [comment]
I tried to fix this yesterday. It seemed as a very easy fix, but unfortunately I get the `tests/API//OVAL/report_variable_values` failing. But I am not

Is it allowed by standard that a textfilecontent54_test contains variable_object as in `oval:x:tst:8` in `tests/API//OVAL/report_variable_values/report_variable_values.def.xml` ?

Schematron validation tells me that it is not allowed.

```
oscap oval validate --schematron report_variable_values.def.xml
<?xml version="1.0"?>
oval:x:tst:8 - the object child element of a textfilecontent54_test must reference a textfilecontent54_object
.......
```

@mpreisler @isimluk Does that mean that we have a wrong OVAL content in our upstream test suite?

**Comment by mpreisler** [comment]
@jan-cerny Certainly looks like that to me.

**Comment by jan-cerny** [comment]
@mpreisler Then I can fix the invalid test content and I can easily create a pull request with a fix for this.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/448/commits/9aef5407580f4e1945e078635271a5dcdb7c12b3
