### ISSUE TITLE
Wrap HTML report's <script> and <style> elements in CDATA

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#441]
To prevent entity warnings.

See https://bugzilla.redhat.com/show_bug.cgi?id=1347367

**Comment by jan-cerny** [comment]
Using <![CDATA[]]> in <style> and <script> elements will not remove all the errors. I  verified it today. Actually xmllint will still report a large amount of errors. That is because HTML document contains tags like <br> which hasn't corresponding end tags (there is no </br>). Such elements will cause xmllint erorrs like "Opening and ending tag mismatch".

I think we should not try to validate HTML using xmlllint, beacuse HTML is not supposed to be a valid XML.

**Comment by mpreisler** [comment]
That is true but doesn't change the fact that we still should wrap in CDATA.

**Comment by jan-cerny** [comment]
@mpreisler You mean that it should be wrapped in resulting HTML or in the XSLT templates?

**Comment by jan-cerny** [comment]
In XSLT templates it's already there. In HTML report it would be an one-liner, but I have never seen such a thing in a HTML document.

**Comment by mpreisler** [comment]
You are correct, CDATA is XML-only.
