### ISSUE TITLE
Not escaped filenames in result file

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#469]
It probably isn't problem of filenames only.
When I create strange filenames to scan, they are not correctly escaped to xml.

```
Entity: line 3457: parser error : PCDATA invalid Char value 27
            <unix-sys:filepath>/tmp/tmp.5mogjwJMK2/filename_</unix-sys:filepa
                                                             ^
```

More info & test:
https://github.com/OpenSCAP/openscap/pull/468

**Comment by jan-cerny** [comment]
I think a similar solution to patch used https://github.com/OpenSCAP/openscap/pull/459 will be helpful here.
However I think we should escape most (?all) of the collected strings that we serialize into XML documents, because a similar issue can appear at many other places (textfilecontent, process58, ...)

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/473/commits/7bde7357ed5f8a1bf1cb3f73bb76a95fd2c7523f
