### ISSUE TITLE
xmlfilecontent_test clubs multiple objects into one

### ISSUE THREAD

**Issue by praving5** [OpenSCAP/openscap#470]
A strange situation. Throughout OVAL schema, if any object definition results in multiple objects, those objects are treated individually.

But, in `xmlfilecontent_test`, my xpath matches 3 node attributes. But, each node is NOT treated individually. Why so? The values are enumerated in the state. 

Check this example from results (why just one item_id with 3 values? why not one value per item_id?):

```
<ind-sys:xmlfilecontent_item id="1155872" status="exists">
            <ind-sys:filepath>/opt/vmware/horizon/workspace/conf/server.xml</ind-sys:filepath>
            <ind-sys:path>/opt/vmware/horizon/workspace/conf</ind-sys:path>
            <ind-sys:filename>server.xml</ind-sys:filename>
            <ind-sys:xpath>/Server/Service/Connector/@connectionTimeout</ind-sys:xpath>
            <ind-sys:value_of>20000</ind-sys:value_of>
            <ind-sys:value_of>20000</ind-sys:value_of>
            <ind-sys:value_of>20000</ind-sys:value_of>
</ind-sys:xmlfilecontent_item>
```

As you see, the xpath`/Server/Service/Connector/@connectionTimeout` matches 3 connectors and values are pulled.

This is problematic because of 2 reasons:

1) How do I check the number of matches? Count does not work on state definitions.
2) Suppose a user removed one of the xpaths, the test will still be true. I cannot ensure that all the xpaths actually existed. If one matches, the test passes.

Is this OVAL schema limitation or bug in OpenSCAP?

**Comment by jan-cerny** [comment]
Hi, for me it looks more like a OVAL limitation. The specification says that it is intended to have xpath matching only one attribute or element, however it is up to content author to define xpath expression, http://oval.mitre.org/language/version5.11/ovalsc/documentation/independent-system-characteristics-schema.html#xmlfilecontent_item

**Comment by praving5** [comment]
ok. Then, let us close.

**Comment by praving5** [comment]
Reopening it. @mpreisler suggested an investigation over email.

**Comment by evgenyz** [comment]
@praving5 What was proposed for investigation?
@jan-cerny Do we have the same problem for `yamlfilecontent`?

**Comment by jan-cerny** [comment]
@evgenyz 

> What was proposed for investigation?

This issue was proposed for investigation :smile:  Martin said in his email that

_"This looks like a bug to me, I recommend reporting it."_

Since at that moment this issue was already reported and closed, the reporter reopened it with the hope that we will investigate it again.

I still think that this behaviour is expected. It is allowed to match multiple text values of elements or attributes. And the textfilecontent_item element can have unlimited amount of `value_of` child elements to populate these values in. That's my interpretation of the OVAL specification.

> Do we have the same problem for yamlfilecontent?

In yamlfilecontent probe the same situation happens. For example, in our test https://github.com/OpenSCAP/openscap/blob/maint-1.3/tests/probes/yamlfilecontent/test_probes_yamlfilecontent_array.xml we have a yamlpath expression `.spec.outputs[0:2].name` which matches 2 values in the corresponding file https://github.com/OpenSCAP/openscap/blob/maint-1.3/tests/probes/yamlfilecontent/openshift-logging.yaml and the result of this is:

```
          <ind-sys:yamlfilecontent_item id="1206573" status="exists">
            <ind-sys:filepath>/tmp/openshift-logging.yaml</ind-sys:filepath>
            <ind-sys:path>/tmp</ind-sys:path>
            <ind-sys:filename>openshift-logging.yaml</ind-sys:filename>
            <ind-sys:yamlpath>.spec.outputs[0:2].name</ind-sys:yamlpath>
            <ind-sys:value_of>elasticsearch</ind-sys:value_of>
            <ind-sys:value_of>elasticsearch-insecure</ind-sys:value_of>
          </ind-sys:yamlfilecontent_item>
```

Notice the 2 value_of elements.
