### ISSUE TITLE
--report should minimize remediation script sections and say what type of remediation script it is

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#519]
When running an oscap scan with the --report option, it is now more difficult to determine what type of scripts the remediation scripts are as the section header just says "Remediation script". This has happened since the addition of ansible scripts to SSG, 

I propose that not only does the Remediation script section header now say something like "Remediation script - Shell", "Remediation script - Puppet", "Remediation script - Ansible", etc., but it also minimizes the "Remediation script" sections so that a user has to expand the section for the script that the user wants to implement.

If this is an ssg issue, let me know.

**Comment by jan-cerny** [comment]
@redhatrises Nice catch and good idea, thanks.

I have noticed that this issue appears not only in the reports, but also in HTML guides that we will ship in RPMs and on openscap portal.

I think this can be fixed in OpenSCAP XSLT templates that are used generate the reports and guides.

After the fix will be done in OpenSCAP, to get the HTML guides fixed it would be necessary to build SSG using the fixed version of OpenSCAP.

**Comment by mpreisler** [comment]
We show the type of remediation since 686fd4104cdcea05cba15de894edf2a6e28da926

**Comment by mpreisler** [comment]
Remediations are collapsible since 4a1e91d7e5995109252e7044aefcc23e9413a876
