### ISSUE TITLE
Use NIST CPEs over customized CPEs

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#544]
OpenSCAP should use NIST CPEs over the use customized CPEs as NIST CPEs are officially accepted CPEs. PR https://github.com/OpenSCAP/openscap/pull/180 is an example of CPEs that should have been NIST provided CPEs instead of customized CPEs. PR https://github.com/OpenSCAP/openscap/pull/539 shows the correct usage for creating a customized CPE as NIST does not have an official CPE for Amazon Linux.

I haven't looked to see if this is technically feasible to code. This may be a documentation awareness or for the PR reviewer to check and validate.

**Comment by mpreisler** [comment]
Definitely agreed. This was an oversight on my part. This is quite challenging to automate so probably we should just all be aware of this and check it when reviewing PRs.

**Comment by jan-cerny** [comment]
Yes, we should definitely prefer the NIST CPEs, at the same time we shouldn't remove existing CPEs from maintenance branches. I agree with @mpreisler to be aware of this issue when reviewing PRs.

This is a more complex problem since some downstreams use unofficial CPEs in their content or os-release packages.

We are using `cpe:/o:redhat:enterprise_linux:7` to cover all RHEL7 minor releases, But NIST uses `cpe:/o:redhat:enterprise_linux:7_X` (where X is the minor version) different for every RHEL7 minor release.

To use official NIST CPEs in our content we would have to add official CPEs for every minor RHEL7 releases. Is that what we want?
