### ISSUE TITLE
Make --verbose/--verbose-log-file "global" argument

### ISSUE THREAD

**Issue by rsprudencio** [OpenSCAP/openscap#603]
I think it doesn't make sense to have --verbose only for XCCDF module, I started moving it to other modules, but I think it might be better to make it a wider range, scoping all modules.

#596 is a sample why this would be better, instead of copying the same code everywhere and the same doc across several different modules.

**Comment by jan-cerny** [comment]
Yes, it makes sense these parameters being global.
For some modules verbose mode will not produce anything helpful or meaningful. I think that's the reason I designed it only in `oval eval` and `xccdf eval`, because I wanted cover the process of OVAL evaluation at first. But covering other modules with debugging messages would be great! 👍

**Comment by rsprudencio** [comment]
I'll try to make --verbose/--verbose-log-file a global option for all modules later and change the manpages.

**Comment by mpreisler** [comment]
@jan-cerny hasn't this been fixed in 1.3.0?

**Comment by jan-cerny** [comment]
@mpreisler Yes, it is fixed in https://github.com/OpenSCAP/openscap/pull/1143
