### ISSUE TITLE
Scanning mounted filesystems without CHROOT

### ISSUE THREAD

**Issue by ilackarms** [OpenSCAP/openscap#778]
Use case:

Currently https://github.com/openshift/image-inspector/ uses OpenSCAP to scan Docker images. Root FS of a Docker image is pulled and extracted to a temp directory. We then run `oscap` commands with env vars set to enable `chroot` to the directory containing the image rootfs (in particular `OSCAP_PROBE_ROOT`).

The problem with this is that it requires `image-inspector` to have permission to run `chroot`. By default, pods (containers) running inside OpenShift are not able to `chroot` and must specifically request this permission.

We'd like to know if it's possible to scan mounted filesystems *without* chroot?

**Comment by jan-cerny** [comment]
Hi @ilackarms ,

I don't think that it's possible to scan mounted filesystems without chroot now. The SCAP content contains hardcoded filepaths to check, eg. `/etc/shadow` and we currently don't have any way to tell OpenSCAP that it should add some prefix to that. We could implement something like "fake chroot", basically adding a prefix to all filepaths. But that wouldn't solve certain problems that are solved by chroot. Eg. it would scan RPM database and systemd dependency from the host.

Main reason why we use chroot is that we can reuse existing SCAP content and tooling only with decent changes, so that we are able to quickly deliver security policies for containers and images as we do for bare-metal machines. Honestly SCAP content is pretty hard to develop due to complexity of the SCAP specifications.

Where is image inspector supposed to be run? On a host system? Inside a container?

How you checked "Atomic scan" ? Atomic scan uses OpenSCAP to scan Docker images for vulnerabilities and configuration compliance as well.

**Comment by ilackarms** [comment]
@jan-cerny image inspector can be run in a number of use case scenarios; typically it's inside a container. this issue came up when trying to run inside of Openshift, as Openshift disables `chroot` permission by default for unprivileged containers. We'd like to permit non-privileged users to run image scans with OpenSCAP

**Comment by mpreisler** [comment]
We do have support for non-chroot offline scanning in OpenSCAP. See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/probe/probe.h#L74

And the rpminfo probe has it implemented as well. I am not sure why we require chroot for the rpm probes, it seems like we can do it without chroot. See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/linux/rpminfo.c#L272

**Comment by mpreisler** [comment]
I did some more research today into what could be used to avoid the `chroot` with `rpminfo` probes.

If the environment variable "OSCAP_PROBE_RPMDB_PATH" is provided and points to an existing `rpmdb` it can be used instead of a chroot. `OSCAP_PROBE_ROOT` must not be provided, otherwise chroot is used even when RPMDB_PATH is provided.

See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/probe/main.c#L310
See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/linux/rpminfo.c#L273

This is only implemented in `rpminfo` and not in `rpmverifyfile` and other RPM probes. However, `rpminfo` should be enough for CVE OVAL feed scanning.

Excerpt from CVE OVAL:
```
  <red-def:rpminfo_test check="at least one" comment="openssl is earlier than 1:1.0.1e-34.el7_0.3" id="oval:com.redhat.rhsa:tst:20140679005" version="601">
   <red-def:object object_ref="oval:com.redhat.rhsa:obj:20140679005"/>
   <red-def:state state_ref="oval:com.redhat.rhsa:ste:20140679003"/>
  </red-def:rpminfo_test>
  <red-def:rpminfo_test check="at least one" comment="openssl is signed with Red Hat redhatrelease2 key" id="oval:com.redhat.rhsa:tst:20140679006" version="601">
   <red-def:object object_ref="oval:com.redhat.rhsa:obj:20140679005"/>
   <red-def:state state_ref="oval:com.redhat.rhsa:ste:20140675001"/>
  </red-def:rpminfo_test>
```

@ilackarms Does this help?

**Comment by ilackarms** [comment]
@jan-cerny interesting; let me try this with our current implementation. Does this mean we can simply substitute `OSCAP_PROBE_ROOT=/path/to/rootfs` with `OSCAP_PROBE_RPMDB_PATH=/path/to/rootfs/path/to/rpmdb` and it will just work? Testing now

**Comment by jan-cerny** [comment]
@ilackarms Looks like it should work, but I have never tried it. Please let us know how what have you encountered during your testing. Thanks.

**Comment by ilackarms** [comment]
```
+ OSCAP_PROBE_OS_VERSION=Unknown
+ OSCAP_PROBE_OS_NAME=Linux
+ OSCAP_PROBE_RPMDB_PATH=/var/tmp/image-content/var/lib/rpm
+ OSCAP_PROBE_ARCHITECTURE=amd64
+ OSCAP_PROBE_PRIMARY_HOST_NAME=docker-image-
+ oscap oval eval --id oval:org.open-scap.cpe.rhel:def:5 /usr/share/openscap/cpe/openscap-cpe-oval.xml
OpenSCAP Error: Probe at sd=32 (system_info) reported an error: Missing value [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Failed to create a new agent session. [oval_session.c:315]
```
tried running the above, resulted in the error shown. Is `/var/lib/rpm` not the location of the rpmdb? Maybe I'm pointing at the wrong destination?

**Comment by mpreisler** [comment]
@ilackarms This works for me:
```
export OSCAP_PROBE_OS_VERSION=Unknown
export OSCAP_PROBE_OS_NAME=Linux
export OSCAP_PROBE_RPMDB_PATH=/var/lib/rpm
export OSCAP_PROBE_ARCHITECTURE=amd64
export OSCAP_PROBE_PRIMARY_HOST_NAME=docker-image-abc

oscap oval eval --id oval:org.open-scap.cpe.rhel:def:5 /usr/share/openscap/cpe/openscap-cpe-oval.xml
```

I am not sure how you are running it but perhaps you need to export the env to the oscap process?

Could you run:
```
oscap oval eval --verbose DEVEL --id oval:org.open-scap.cpe.rhel:def:5 /usr/share/openscap/cpe/openscap-cpe-oval.xml
```

So that we get more info?

**Comment by mpreisler** [comment]
OK, I may be wrong and it may actually not work. The devel messages aren't great, we definitely need to improve this.

**Comment by ilackarms** [comment]
I will need time to bring up my chroot-restricted environment again (requires running openscap inside of an openshift pod). I will update here when I have the chance

**Comment by jan-cerny** [comment]
@mpreisler `export OSCAP_PROBE_RPMDB_PATH=/var/lib/rpm` That points to the host? Haven't you scan the host?

**Comment by mpreisler** [comment]
@ilackarms could you please check out PR #808? It should solve your use-case. This patch is included in the latest OpenSCAP 1.2.15 release. Let us know if you need anything else.

**Comment by ilackarms** [comment]
@mpreisler thank you! I'll try it out this weekend

**Comment by ilackarms** [comment]
@mpreisler it's not clear how to make use of the 1.2.15 release. Am I correct that I need to build from source?

**Comment by jan-cerny** [comment]
@ilackarms Version 1.2.15 is already available in both Fedora 25 and 26. Is there any problem with installing it?

**Comment by ilackarms** [comment]
@jan-cerny sorry, noob question. how do you install from the release tarball? it seemed to me like you still need to `configure` and `make`. which is failing for me

**Comment by jan-cerny** [comment]
If you want to build OpenSCAP directly from the release tarball, you have to install all the build dependencies, build the code and install. It is described here in https://github.com/OpenSCAP/openscap/blob/maint-1.2/README.md
in "Compilation" section.

On RHEL you can make use of 
https://copr.fedorainfracloud.org/coprs/openscapmaint/openscap-latest/
instead of manual build.
