### ISSUE TITLE
./src/OVAL/oval_session.c portability question

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#826]
Hi,

Line 30: `#include <linux/limits.h>`

Is this include really required on Linux?
If so, this statement should probably be enclosed by a `#if defined(__linux__) ... #endif` or the like or maybe `#include <limits.h>` is just sufficient.
Otherwise shouldn't this line be just removed?

Jean-Louis Charton

**Comment by jan-cerny** [comment]
Hi @jlcharton 

`linux/limits.h` and `limits.h` are different files with different content. It's here because of `PATH_MAX` macro used on line 429. See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/oval_session.c#L429

If I remove this `#include` it still compiles without any problem on my Fedora machine. However I have found that this `#include` is introduced by ebe4880dc34742a010a082694070ac1943a2fa21 which deals with portability to SUSE. So removing it could break compilation on SUSE.

It looks like that the solution would be to enclose it by `#if defined ...`

**Comment by jan-cerny** [comment]
Fixed by https://github.com/OpenSCAP/openscap/pull/827
