### ISSUE TITLE
failed to fetch remote resources

### ISSUE THREAD

**Issue by vassilisp** [OpenSCAP/openscap#883]
> Failed to download "https//www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2"!

The download link is missing the double colon after "https".

The link looks like it is correct in the ds file:

```
ssg-centos7-ds.xml
54124:                <ns1:check-content-ref href="https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2" />
149160:              <ns2:check-content-ref href="https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2" />
```

So somewhere, the double colon is removed.

OpenSCAP command line tool (oscap) 1.2.13
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.
```
==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
```

SSG is v0.1.35
OS is rhel6

**Comment by jan-cerny** [comment]
Hi, I'm afraid I can't reproduce your issue. The download should work in 1.2.13. I verified that on my RHEL6.9 machine. Which command are you exactly running? Does the output say something else?

Also, using CentOS7 datastream on RHEL6 looks wrong.

**Comment by vassilisp** [comment]
Hi,
RHEL6 is the scanning host. I forgot to mention I am using the SCAP workbench (v1.1.1).
CentOS7 is the target host that is scanned.

```
16:14:20 
info     
Connection established.

16:14:20 
info     
Querying capabilities on remote machine...

16:14:20 
info     
Copying input data to remote target...

16:14:22 
info     
Starting the remote process...

16:14:22 
info     
Processing on the remote machine...

16:14:22 
info     
Downloading of "http//www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml"...

16:14:22 
warning  
Failed to download "http//www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml"!

16:14:22 
warning  
The 'oscap' process has written the following content to stderr: WARNING: Skipping http://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml file which is referenced from XCCDF content 

16:14:50 
info     
Cleaning up...

16:14:51 
info     
Processing has been finished!
```

**Comment by vassilisp** [comment]
I just noticed that the remote host (CentOS7) has openscap v.1.2.10 installed. Could that be the issue?

**Comment by jan-cerny** [comment]
I have noticed few things:
* With 1.2.10 and SSG 0.1.35 it works for me as well, but I am on Fedora.
* It tries to download "*.xml" file, not the "*.bz2" file. Last version of SSG that did that was 0.1.30. @yuumasato, @redhatrises  Is it possible that SSG 0.1.35 contains link to uncompressed XML instead of bzip2?
* plain HTTP version of the XML document doesn't exist anymore. Only HTTPS is available. attempt to download leads to `HTTP/1.1 302 Moved Temporarily`. I think that OpenSCAP can't handle that, so it leads to an error. 
* Remote resources are downloaded on the target machine. The oscap-ssh is just a stupid wrapper.  You're right that's a big problem if the target hasn't got a direct access. However you can download the OVAL stream manually on the local host and run a separate evaluation just for vulnerability scan. @mpreisler Could we improve this?
* I can't figure out how is that done in SCAP Workbench.  @mpreisler or @WesleyCeraso , could you help? Does SCAP Workbench download all the referenced content?
* @vassilisp Do you really have ssg 0.1.35?

**Comment by vassilisp** [comment]
hmm, you are right, I was using an older SSG even though I compiled SSG v0.1.35 two days ago.
Using the correct SSG v0.1.35, I now get the correct bzip2 file but again it fails to download it since the scanned target doesn't have direct access.

```
Starting the evaluation...
Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 ... error
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content

```
For the moment I do exactly what you described, I download the OVAL stream manually and scan the target using that.

For me then the open issue is if it is possible for open-ssh to download the remote references locally and then use them to scan the remote target.

Thanks for all the help and for taking the time to reply.

**Comment by Sudermoni** [comment]
The answer is very simple. Please set the proxy of your node/server on where you performing this will resolve this issue. I have done the same and it all worked fine for me now.

# export "https_proxy=<proxy server>:<portnumber>"

**Comment by evgenyz** [comment]
I think that this issue should be closed as it is. And either another RFE about `oscap-ssh` support for downloading resources (and uploading them to the target) in this repo should be created. Or, alternatively, RFE about support of extra options for remote scan (e.g. **https_proxy=**) should be opened in https://github.com/OpenSCAP/scap-workbench repo.
