### ISSUE TITLE
oscap-ssh returns permission denied when downloading results from a system that has had remediations applied

### ISSUE THREAD

**Issue by ghost** [OpenSCAP/openscap#935]
Description:
The oscap-ssh tool has the option to scan a remote system using a normal user with the --sudo option.  This option is necessary because a system that has already had remediations applied and is being scanned for compliance will not allow direct root logins.  However, a system that has had remediations applied will also have the umask set to 077, which means any files written by root will not be readable by any user on the system, including the user that you logged in as.  This results in the output report.html and results.xml failing to download back to the machine that initiated the scan

Steps to reproduce:
1. Run remediations on a system that include setting umask to 077 and disallowing direct root logins over ssh.

2. Scan the remote machine using the sudo option
oscap-ssh --sudo regularuser@remote-machine 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_nist-800-171-cui --results results.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml

Expected output:
results.xml and report.html are downloaded to the machine that initiated the scan.

Actual output:
Shared connection to remote-machine closed.
oscap exit code: 2
Copying back requested files...
scp: /tmp/tmp.9eGzukNHee/results.xml: Permission denied
Failed to copy the results file back to local machine!

Cause:
The remediated system has a umask of 077, which causes the files to not be readable by the user that performed the scan.
bash-4.2# cd /tmp/tmp.9eGzukNHee/
bash-4.2# ls -al
total 18244
drwx------.  2 regularuser regularuser     4096 Dec 13 10:45 .
drwxrwxrwt. 13 root   root       4096 Dec 13 10:44 ..
-rw-------.  1 portal portal 11839886 Dec 13 10:44 input.xml
-rw-------.  1 root   root    3348719 Dec 13 10:45 report.html
-rw-------.  1 root   root    3480675 Dec 13 10:45 results.xml

Suggested fix:
before attempting to download, oscap-ssh should run the following command:
chmod go+r /tmp/<temp directory>/*
This will ensure that the files can be read by the non root user and downloaded to the system that initiated the scan.

**Comment by polachz** [comment]
This is caused by strict default umask, probably 027 in your case (same as me)
Solution is in sudoers file.
To run oscap on remote system, you have to allow sudo for oscap command.
Add here umask_override, umask=022

my /etc/sudoers.d/99-oscap content:

# allow oscap-user to run openscap scanner 
Defaults!/usr/bin/oscap !requiretty, umask_override, umask=022
<my_user_name> ALL=(root) NOPASSWD: /usr/bin/oscap

hope this helps

**Comment by nathanpeters008** [comment]
If you look at the description, I already state that the umask of 077 is the issue.  The scanner should account for this and run chmod on the files, considering it is designed to scan systems that have had remediations applied.  You should not be required to override a umask in the sudoers file to work around this.

**Comment by polachz** [comment]
@nathanpeters008 
I think that you are wrong, because  oscap-ssh can't change file owner or access rights on the remote server by this way. If you take look on results.xml etc, then files are owner by root/root and has rw rights just for root account. Then you have to run chmod as root (with sudo) to put read rights for everyone. Under regular user account you will get access denied error. Then you have to grant sudo access for chmod in sudoers on remote server, by same way as for /usr/bin/oscap. Or you can run everything as root, but it's big security hole to the system
Anyway, you have to grant r+ permissions for report etc. 
My way just change umask for /usr/bin/oscap call, other commands uses default umask granted to root. Then you avoid sudo chmod requirement here by easy way.
But, o

**Comment by shawndwells** [comment]
I'm able to duplicate this. 

Using the following:
``
oscap-ssh --sudo shawn@myhost 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_nist-800-171-cui --results results.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
``

On systems with 022 umask:
``$ ll
total 15268
-rw-r--r--. 1 shawn shawn 11963926 Jan 30 23:05 input.xml
-rw-r--r--. 1 root  root   3668742 Jan 30 23:08 results.xml
``

And when I switch to 077:
``
# ls /tmp/tmp.knoxl1fCsH/ -l
total 18876
-rw-------. 1 shawn shawn 11963926 Jan 30 23:11 input.xml
-rw-------. 1 root  root   3690847 Jan 30 23:14 report.html
-rw-------. 1 root  root   3668742 Jan 30 23:14 results.xml
``

Definitely a usability issue. This really isn't a bug (umask is doing what it should).... but we still need to get reports back to originating host. 

Could oscap-ssh keep results in memory, socket them back to initiating host, and write a results file locally?

**Comment by nathanpeters008** [comment]
@polachz oscap-ssh most definitely can chmod the files.  That's exactly what the --sudo option is for.  If it can run the report as root (with the --sudo option), then while it has those sudo privileges, it most certainly can chmod the files before it drops those privileges.

**Comment by polachz** [comment]
@nathanpeters008 
oscap-ssh runs on local machine  and uses SSH to start commands on the remote host. It's just bash script. open it in text editor and take a look. Here is how it's exactly works with sudo:

ssh -o ControlPath="$MASTER_SOCKET" $SSH_ADDITIONAL_ARGS -p "$SSH_PORT" "$SSH_HOST" "**$OSCAP_SUDO** oscap ${args[*]}" 

It's same as you fire sudo oscap in the interactive ssh session.  If you not modify sudoers file on the remote host to alow sudo without password entry, you don't start oscap remotely with admin privilege and oscap-ssh

see man page form oscap-ssh
[https://www.mankier.com/8/oscap-ssh#Exemplary_Usage-Running_remotely_as_root](url)

You can modify your oscap-ssh script easily to try use the chmod as you proposed and try: )
As I said, it's just bash script

For your proposed solution, you have to grant sudo NOPASSWD for chmod command. it's something what  I really don't need  on my production server.

**Comment by nathanpeters008** [comment]
@polachz You are missing the point.  I know how the script works.  Since the actual work is done by the oscap scanner on the remote system, the modification would obviously be to the oscap scanner to run chmod internally while it's running with sudo permissions after it drops the files in the temp directory, and before it disconnects and scp is invoked to return the files.

In fact, you can see a sample script I posted at the beginning of January to deal with a similar issue while I wait for a modification to the actual oscap or oscap-ssh program in this thread: https://github.com/OpenSCAP/openscap/issues/863

I never suggested that the password prompting should be altered.  I personally don't have an issue with the password prompt for sudo that I currently get from the scanner when running with the --sudo flag.  In fact, modifying the remote system with NOPASSWD in the sudoers file would actually cause it to fail on one of the tests that ensures that option does not exist and would drop your overall score for whatever profile you are scanning against.

If running it without a password prompt is so important to you, just wrap it with python's fabric or some other mechanism that caches sudo passwords and automatically provides them when they detect a sudo prompt.  That way you never have to deal with the NOPASSWD issue dropping your score and get similar functionality.

**Comment by defionscode** [comment]
@shawndwells I dont know that writing to memory (tempfs or ramdisk) will help, IIRC both mechanisms will still be influenced by umask settings.
