### ISSUE TITLE
oscap: unrecognized option '--rule'

### ISSUE THREAD

**Issue by ghost** [OpenSCAP/openscap#936]
According to the openscap 1.2 documentation here : https://static.open-scap.org/openscap-1.2/oscap_user_manual.html
`
You can additionaly add --rule option to the above command to evaluate a specific rule:
$ oscap xccdf eval --profile Desktop --rule ensure_gpgcheck_globally_activated  --results xccdf-results.xml --cpe cpe-dictionary.xml scap-xccdf.xml
`
However, attempting to actually use the --rule flag fails:
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_nist-800-171-cui --rule content_rule_aide_build_database --results results.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
oscap: unrecognized option '--rule'
Usage:    oscap [options] xccdf eval [options] INPUT_FILE [oval-definitions-files]
Help:     oscap xccdf eval -h

yum list installed openscap-scanner
Installed Packages
openscap-scanner.x86_64  1.2.14-2.el7

The help does not show this option as being valid either.
oscap xccdf eval --help
oscap -> xccdf -> eval

Perform evaluation driven by XCCDF file and use OVAL as checking engine

Usage: oscap [options] xccdf eval [options] INPUT_FILE [oval-definitions-files]

INPUT_FILE - XCCDF file or a source data stream file

Options:
   --profile <name>     	 - The name of Profile to be evaluated.
   --tailoring-file <file>       - Use given XCCDF Tailoring file.
   --tailoring-id <component-id> - Use given DS component as XCCDF Tailoring file.
   --cpe <name> 		 - Use given CPE dictionary or language (autodetected)
                		   for applicability checks.
   --oval-results       	 - Save OVAL results as well.
   --sce-results		 - Save SCE results as well. (DEPRECATED! use --check-engine-results)
   --check-engine-results        - Save results from check engines loaded from plugins as well.
   --export-variables   	 - Export OVAL external variables provided by XCCDF.
   --results <file>     	 - Write XCCDF Results into file.
   --results-arf <file> 	 - Write ARF (result data stream) into file.
   --thin-results       	 - Thin Results provides only minimal amount of information in OVAL/ARF results.
                        	   The option --without-syschar is automatically enabled when you use Thin Results.
   --without-syschar    	 - Don't provide system characteristic in OVAL/ARF result files.
   --report <file>      	 - Write HTML report into file.
   --skip-valid 		 - Skip validation.
   --fetch-remote-resources      - Download remote content referenced by XCCDF.
   --progress   		 - Switch to sparse output suitable for progress reporting.
                		   Format is "$rule_id:$result\n".
   --datastream-id <id> 	 - ID of the datastream in the collection to use.
                        	   (only applicable for source datastreams)
   --xccdf-id <id>      	 - ID of component-ref with XCCDF in the datastream that should be evaluated.
                        	   (only applicable for source datastreams)
   --benchmark-id <id>  	 - ID of XCCDF Benchmark in some component in the datastream that should be evaluated.
                        	   (only applicable for source datastreams)
                        	   (only applicable when datastream-id AND xccdf-id are not specified)
   --remediate  		 - Automatically execute XCCDF fix elements for failed rules.
                		   Use of this option is always at your own risk.
   --verbose <verbosity_level>   - Turn on verbose mode at specified verbosity level.
   --verbose-log-file <file>     - Write verbose informations into file.

Is this a feature that was documented but never added, or a feature that was removed and the documentation just not updated to reflect that?

**Comment by nathanpeters008** [comment]
I had a look through the source code and commit history and realized that the --rule option is included in 1.2.15 (https://github.com/OpenSCAP/openscap/releases/tag/1.2.15)

Unfortunately, the instructions in the manual seem based around using the built-in OS repositories.  In order to actually use that feature, you need to either build from source or enable COPR.

I feel like the manual should only reference functionality that is available in the @base repository.  I'm not sure if there is any way to keep an older version of the manual online and release the updated manual at the same time that @base is updated to include the 1.2.15 or higher release though.  Is there a way to have the online manual versioning more granular (ie, 1.2.15 instead of just 1.2) so it is more clear exactly which version the manual is referring to?

**Comment by jan-cerny** [comment]
Hello @nathanpeters008 

Yes, the --rule option was added in 1.2.15.

The user manual is part of the upstream project and we update it after every release. When we add a new feature we sometimes document it there.

It would be tricky to document only something that is already in repositories, because different Linux distributions ship different versions of OpenSCAP. For example Fedora has 1.2.16, Debian has 1.2.9.

I appreciate your idea. I think it shouldn't be a problem to publish multiple versions of user manual on the website. We should be specific to which version of OpenSCAP is the manual applicable. We should let user choose the document for his version of OpenSCAP.

**Comment by nathanpeters008** [comment]
here is a great example of granular docs : https://docs.docker.com/docsarchive/

You can choose minor version numbers from there
